### ISSUE TITLE
No Hyphenssymbol

### ISSUE THREAD

**Issue by maerlynflagg** [nikitadol/hyphenator#2]
i tried to use the plugin in flutter, but there is no effect. 

```
      var loader = await DefaultResourceLoader.load(DefaultResourceLoaderLanguage.de1996);
      hyphenator = Hyphenator(resource: loader);

     var y = hyphenator.hyphenate('anyGermanWordHere');
```

no word get the default 'hyphenateSymbol'. so i debugged my code and i saw after creation of the Hyphenator, the symbol is this "" and not the default one '\u{00AD}' (look to screenshot of debugging).

same with this:

`var y = _hyphenator.hyphenateWord('anyGermanWordHere');`

is this a bug or something wrong with this code?

![hyphenator_error](https://user-images.githubusercontent.com/13437496/81077985-f1012980-8eed-11ea-817e-736a91c64289.jpg)

**Comment by nikitadol** [comment]
Hi.

'\u{00AD}' - invisible character

But he is in the line
![image](https://user-images.githubusercontent.com/16593680/81079431-3591c280-8ef8-11ea-8d83-3cd945daa9f8.png)

**Comment by maerlynflagg** [comment]
Hello,

okay i understand. i checked up the displayed text on screen and it worked. i was confused, because i expected on the displayed text a '-' for the german language. for example:  

Klei-
dung

so thanks, no bug. :)
